# Generated by Django 5.2.3 on 2025-06-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_message_options_message_read_room_is_private_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
